//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace buzplan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoCodes
    {
        public long Id { get; set; }
        public string Descr { get; set; }
        public string Code { get; set; }
        public string Nuts { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string EE { get; set; }
        public string EE_Descr { get; set; }
        public int Level { get; set; }
    }
}
